# Generated by Django 5.0.4 on 2024-05-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rain', models.IntegerField()),
                ('light', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
